const c=document.getElementById('canvas'),ctx=c.getContext('2d'),img=new Image();let loaded=false,mode='',angle=0,flipped=false,drawing=false,strokes=[],items=[];
file.onchange=e=>{const f=e.target.files[0];if(!f)return;img.onload=()=>{loaded=true;empty.style.display='none';angle=0;flipped=false;c.width=img.naturalWidth;c.height=img.naturalHeight;draw()};img.src=URL.createObjectURL(f)};
[bright,contrast,sat,hue,blur].forEach(el=>el.oninput=draw);
function tab(id){document.querySelectorAll('.toolset').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden')}
function preset(m){mode=m;draw()}
function filterString(){let f=`brightness(${bright.value}%) contrast(${contrast.value}%) saturate(${sat.value}%) hue-rotate(${hue.value}deg) blur(${blur.value}px)`;if(mode==='anime')f+=' saturate(155%) contrast(125%)';if(mode==='neon')f+=' saturate(200%) contrast(135%) hue-rotate(18deg)';if(mode==='manga')f+=' grayscale(100%) contrast(160%)';if(mode==='dream')f+=' brightness(112%) saturate(120%)';if(mode==='vivid')f+=' saturate(175%) contrast(115%)';if(mode==='mono')f+=' grayscale(100%)';if(mode==='night')f+=' brightness(65%) hue-rotate(205deg) saturate(140%)';if(mode==='warm')f+=' sepia(28%) saturate(130%)';return f}
function draw(){if(!loaded)return;let w=img.naturalWidth,h=img.naturalHeight;if(Math.abs(angle)%180===90){c.width=h;c.height=w}else{c.width=w;c.height=h}ctx.save();ctx.clearRect(0,0,c.width,c.height);ctx.translate(c.width/2,c.height/2);ctx.rotate(angle*Math.PI/180);ctx.scale(flipped?-1:1,1);ctx.filter=filterString();ctx.drawImage(img,-w/2,-h/2,w,h);ctx.restore();ctx.filter='none';if(mode==='anime'||mode==='neon'){ctx.globalAlpha=.12;ctx.fillStyle=mode==='anime'?'#a74cff':'#008dff';ctx.fillRect(0,0,c.width,c.height);ctx.globalAlpha=1}items.forEach(it=>{ctx.save();ctx.font=`${it.size}px Orbitron`;ctx.fillStyle=it.color;ctx.shadowColor='#a94cff';ctx.shadowBlur=it.glow?14:0;ctx.textAlign='center';ctx.fillText(it.text,c.width/2+it.x,c.height/2+it.y);ctx.restore()});strokes.forEach(s=>{ctx.beginPath();ctx.lineWidth=s.size;ctx.lineCap='round';ctx.strokeStyle='#b65cff';ctx.moveTo(s.pts[0][0],s.pts[0][1]);s.pts.slice(1).forEach(p=>ctx.lineTo(p[0],p[1]));ctx.stroke()})}
function rotate(){if(!loaded)return;angle=(angle+90)%360;draw()}function flip(){if(!loaded)return;flipped=!flipped;draw()}function crop(){if(!loaded)return;let side=Math.min(img.naturalWidth,img.naturalHeight),sx=(img.naturalWidth-side)/2,sy=(img.naturalHeight-side)/2;let temp=document.createElement('canvas');temp.width=temp.height=side;temp.getContext('2d').drawImage(img,sx,sy,side,side,0,0,side,side);img.src=temp.toDataURL();img.onload=()=>{angle=0;flipped=false;draw()}}
function addText(){if(!loaded||!text.value.trim())return;items.push({text:text.value,size:+size.value,x:0,y:0,color:'#fff',glow:true});text.value='';draw()}
function sticker(s){if(!loaded)return;items.push({text:s,size:90,x:0,y:0,color:'#b65cff',glow:true});draw()}
function toggleDraw(){drawing=!drawing;c.style.cursor=drawing?'crosshair':'default'}function pos(e){let r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]}c.addEventListener('pointerdown',e=>{if(!drawing)return;let p=pos(e);strokes.push({size:+brush.value,pts:[p]});c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drawing||!strokes.length)return;strokes.at(-1).pts.push(pos(e));draw()});function clearDraw(){strokes=[];draw()}
function resetAll(){mode='';angle=0;flipped=false;items=[];strokes=[];bright.value=100;contrast.value=100;sat.value=100;hue.value=0;blur.value=0;draw()}
function download(){if(!loaded)return;const a=document.createElement('a');a.download='samrat-studio-edit.png';a.href=c.toDataURL('image/png');a.click()}